version: 2.1

orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4  # Only for Cloudsmith API key management, not Elixir

jobs:
  fetch_deps_job:
    docker: # Changed from 'executor' to 'docker'
      - image: cimg/elixir:1.14.0-node  # Elixir 1.15.7 with Erlang 26, Alpine-based
    environment:
      MIX_ENV: test
      HEX_HTTP_TIMEOUT: "240"  # 240 seconds timeout to avoid fetch failures
      # Set these in CircleCI Project Environment Variables:
      # - CLOUDSMITH_API_KEY: Your Cloudsmith API key
      # - CLOUDSMITH_OWNER: Your Cloudsmith org/username
      # - CLOUDSMITH_HEX_REPO_SLUG: Your repo slug
    steps:
      - checkout  # Get your code from the repo
      - cloudsmith/ensure-api-key  # Makes sure the Cloudsmith API key is available
      - run:
          name: "Set up Hex and Cloudsmith Repo"
          command: |
            # Install/update Hex and Rebar
            mix local.hex --force
            mix local.rebar --force

            # Replace this with your actual SHA fingerprint
            # FINGERPRINT_TO_USE="tp+evxSZS0HnfF7VBSeaMErtJP2R4bleeiWW6QBJ+i4"

            # Add your Cloudsmith repo to Hex
            # mix hex.repo add hexrepo \
            #   "https://hex.cloudsmith.io/${CLOUDSMITH_OWNER}/${CLOUDSMITH_HEX_REPO_SLUG}/" \
            #   --auth-key "${CLOUDSMITH_API_KEY}" \
            #   --fetch-public-key SHA256:tp+evxSZS0HnfF7VBSeaMErtJP2R4bleeiWW6QBJ+i4

            mix hex.repo remove hexpm || true

            mix hex.repo add hexrepo https://hex.cloudsmith.io/orgcs/hexrepo \
              --auth-key "${CLOUDSMITH_API_KEY}" \
              --fetch-public-key SHA256:tp+evxSZS0HnfF7VBSeaMErtJP2R4bleeiWW6QBJ+i4

            # Show current repos and config for debugging
            echo "Hex repos:"; mix hex.repo list
            echo "Hex config:"; mix hex.config
      - run:
          name: Confirm Hex registry source
          command: mix hex.repo list

      - run:
          name: "Fetch Dependencies"
          command: |
            mix deps.get  # Fetch all dependencies, including hackney

workflows:
  fetch_deps_workflow:
    jobs:
      - fetch_deps_job