version: 2.1

orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
  elixir: circleci/elixir@3.1.0 # Re-added as per image

jobs:
  create_and_publish_hex_package_job: # This job creates and publishes the package
    docker: # Corrected executor syntax as per image
      - image: cimg/elixir:1.14.0-node # Example Elixir image with Node.js for broader compatibility
    environment:
      MIX_ENV: prod # Typically publish with prod environment
      HEX_HTTP_TIMEOUT: "240"
      # CLOUDSMITH_API_KEY, CLOUDSMITH_OWNER, CLOUDSMITH_HEX_REPO_SLUG
      # These must be set in CircleCI Project Environment Variables
    steps:
      - checkout
      - run:
          name: "Install Hex & Mix versions"
          command: |
            mix local.hex --force
            mix local.rebar --force
      - run:
          name: "Configure Cloudsmith Hex Mirror"
          command: |
            mix hex.repo add my_cloudsmith_hex_repo \
              "https://hex.cloudsmith.io/${CLOUDSMITH_OWNER}/${CLOUDSMITH_HEX_REPO_SLUG}/" \
              --auth-key "${CLOUDSMITH_API_KEY}" \
              --fetch-public-key "SHA256:${FINGERPRINT}" \
              --force
            mix local.rebar --force # Duplicated as per image
      - run:
          name: "Install Deps"
          command: mix deps.get
      - run:
          name: "Compile Project"
          command: mix compile

workflows:
  version: 2 # Workflow version as per image
  test: # Workflow name as per image
    jobs:
      - create_and_publish_hex_package_job